# Generated by Django 4.2.15 on 2025-12-01 17:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Müşterinin adı', max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(help_text='Müşterinin soyadı', max_length=100, verbose_name='Soyad')),
                ('phone', models.CharField(help_text='Müşteri telefon numarası', max_length=20, unique=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, help_text='Müşteri e-posta adresi', max_length=254, null=True, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, help_text='Müşteri adresi', null=True, verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, help_text='Müşteri aktif mi?', verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, help_text='Müşteri hakkında ek notlar', null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('DEBT', 'Borç'), ('CREDIT', 'Alacak')], default='DEBT', help_text='Borç mu, alacak mı?', max_length=10, verbose_name='Tür')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Borç/Alacak tutarı', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar')),
                ('description', models.TextField(blank=True, help_text='Borç/Alacak açıklaması', null=True, verbose_name='Açıklama')),
                ('is_paid', models.BooleanField(default=False, help_text='Borç ödendi mi?', verbose_name='Ödendi')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Borç ödeme tarihi', null=True, verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('due_date', models.DateField(blank=True, help_text='Borç vade tarihi', null=True, verbose_name='Vade Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='backend.customer', verbose_name='Müşteri')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_debts', to=settings.AUTH_USER_MODEL, verbose_name='Ödeyen')),
            ],
            options={
                'verbose_name': 'Borç/Alacak',
                'verbose_name_plural': 'Borçlar/Alacaklar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='backend_deb_custome_1f892e_idx'), models.Index(fields=['is_paid'], name='backend_deb_is_paid_298af8_idx'), models.Index(fields=['debt_type'], name='backend_deb_debt_ty_94d2c3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='backend_cus_phone_a18d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='backend_cus_created_f84d98_idx'),
        ),
    ]
