# Generated by Django 4.2.15 on 2025-12-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resim başlığı', max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, help_text='Resim açıklaması', null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(help_text='Galeri resmi', upload_to='gallery/', verbose_name='Resim')),
                ('is_active', models.BooleanField(default=True, help_text='Resim aktif mi?', verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, help_text='Gösterim sırası (küçük sayı önce gösterilir)', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gallery_images', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Galeri Resmi',
                'verbose_name_plural': 'Galeri Resimleri',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='backend_gal_created_42104e_idx'), models.Index(fields=['is_active'], name='backend_gal_is_acti_0b8ba1_idx')],
            },
        ),
    ]
