# Generated by Django 5.1.4 on 2025-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Gönderenin adı ve soyadı', max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(help_text='Gönderenin e-posta adresi', max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, help_text='Gönderenin telefon numarası', max_length=20, null=True, verbose_name='Telefon')),
                ('message', models.TextField(help_text='Gönderilen mesaj', verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, help_text='Mesaj okundu mu?', verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at', '-is_read'],
                'indexes': [models.Index(fields=['-created_at'], name='backend_con_created_f78342_idx'), models.Index(fields=['is_read'], name='backend_con_is_read_303f55_idx')],
            },
        ),
    ]
